#include "stdafx.h"

#define MP_ROOT_FILE		0
#define MP_ROOT_VIEW		1
#define MP_ROOT_DEVICES		2
#define MP_ROOT_TOOLS		3
#define MP_ROOT_ENVIRONMENT	4
#define MP_ROOT_WINDOW		5
#define MP_ROOT_HELP		6

#define MP_FILE_NEW			0
#define MP_FILE_OPEN		1	
#define MP_FILE_SAVEAS		2
#define MP_FILE_ARCHVIEPATH	3
#define MP_FILE_CLOSE		4
#define MP_FILE_EXIT		5

#define MP_VIEW_ALGORITHMEDITOR		0
#define MP_VIEW_COMMANDPROMPT		1
#define MP_VIEW_DATABAR				2
#define MP_VIEW_HISTOGRAMVIEW		3
#define MP_VIEW_MANIFEST			4
#define MP_VIEW_PROPERTYMANAGER		5
#define MP_VIEW_XBOXLINKER			6

#define MP_DEVICES_CAMERAPROPERTIES		0
#define MP_DEVICES_CELLSTRETCHER		1
#define MP_DEVICES_STAGEPROPERTIES		2	
#define MP_DEVICES_ZEISSMICROSCOPE		3


#define MP_WINDOW_CASCADE		0
#define MP_WINDOW_TILE_HORZ		1
#define MP_WINDOW_TILE_VERT		2

DWORD InitializeMenuBar(HWND hParent);