//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RACE.rc
//
#define IDC_MYICON                      2
#define IDD_RACE_DIALOG                 102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_RACE                        107
#define IDI_SMALL                       108
#define IDC_RACE                        109
#define IDR_MAINFRAME                   128
#define IDI_NEURON                      131
#define IDI_NEURON2                     132
#define IDI_CARD                        133
#define IDD_FILTERS                     134
#define IDI_PLAY                        135
#define IDB_BITMAP1                     137
#define IDB_BITMAP2                     140
#define IDD_PROPERTYMANAGER             142
#define IDD_XBOXLINKER                  143
#define IDC_CURSOR1                     144
#define IDB_BITMAP3                     145
#define IDD_ALGWIZARD                   146
#define IDD_CAMERAPROPERTIES            147
#define IDI_ICON1                       150
#define IDI_ICON2                       151
#define IDI_ICON3                       152
#define IDD_CELLSTRETCHER               153
#define IDD_STAGEPROPERTIES             154
#define IDI_ICON4                       155
#define IDR_HTML1                       156
#define IDD_EXPERIMENT                  157
#define IDD_MOSAIC                      158
#define IDD_AUTOFOCUS                   159
#define IDD_AXIOVERT                    160
#define IDD_REEFWATCHDOG                161
#define IDD_RW_LIGHTING                 161
#define IDD_ZSTACK                      162
#define IDD_MULTICHANNEL                163
#define IDD_RW_DOSING                   164
#define IDD_DIALOG1                     165
#define IDD_RW_DEVICE                   165
#define IDD_DIALOG2                     167
#define IDD_OBJECTIVE                   167
#define IDD_PARTICLETRACKER             168
#define IDD_LM_TRACKER                  168
#define IDD_DIALOG3                     170
#define IDD_UNO32                       170
#define IDD_SC10LINKER                  171
#define IDD_UNO33                       174
#define IDD_LM_STAGE                    174
#define IDD_LM_ZSTACK                   176
#define IDD_LM_SYSTEM                   177
#define IDD_LM_DEVICE                   179
#define IDD_LM_DISPLAY                  180
#define IDD_LM_PARTICLETRACKER          182
#define IDD_AUTOFOCUS1                  183
#define IDD_LM_AUTOFOCUS                183
#define IDD_TIMELAPSEPROPERTIES         184
#define IDD_TIMELAPSE                   186
#define IDD_HOLOPROPERTIES              187
#define IDD_LM_HOLO                     187
#define IDD_MOTORWATCHDOG               188
#define IDC_EDIT1                       1000
#define IDC_COMBO_CAMERA                1001
#define IDC_YFOV                        1001
#define IDC_EDIT_VELOCITY               1001
#define IDC_EDIT4                       1001
#define IDC_EDIT_COLS                   1001
#define IDC_EDIT_DISTSLICE              1001
#define IDC_EDIT_DIAMETER               1001
#define IDC_EDIT_EXPOSURE               1002
#define IDC_EDIT5                       1002
#define IDC_EDIT_X                      1002
#define IDC_SPLIT1                      1003
#define IDC_EDIT3                       1004
#define IDC_ZFOV                        1004
#define IDC_EDIT_PATH                   1004
#define IDC_EDIT_POS_ABSOLUTE           1004
#define IDC_EDIT_CW                     1004
#define IDC_EDIT_A                      1004
#define IDC_XFOV                        1005
#define IDC_EDIT_POS_RELATIVE           1005
#define IDC_EDIT_RB                     1005
#define IDC_EDIT_B                      1005
#define IDSET                           1006
#define IDC_EDIT_MIX                    1006
#define IDC_EDIT_C                      1006
#define IDC_EDIT_UV                     1007
#define IDC_EDIT_D                      1007
#define IDC_COMBO1                      1008
#define IDC_COMBO_ALGORITHM             1008
#define IDC_BUTTON_LOOP                 1009
#define IDC_BUTTONADD                   1009
#define IDC_BUTTON_STREAM               1009
#define IDC_BTN_EXPAND_JOG              1009
#define IDC_BTN_AUTOFOCUS               1009
#define IDC_BUTTON_START                1009
#define IDC_BTN_REFRESH                 1009
#define IDC_BTN_SET                     1009
#define IDC_BTN_JOG                     1009
#define IDC_BTN_ZERO                    1009
#define IDC_BTN_CALCREFERENCE           1009
#define IDC_BTN_CREATE                  1009
#define IDC_BTN_STREAM                  1009
#define IDC_EDIT_LOOP                   1010
#define IDC_BUTTON_SAVE                 1010
#define IDC_BTN_SAVE                    1010
#define IDC_LIST                        1011
#define IDC_LIST_RESOURCES              1011
#define IDC_LIST_STUDIES                1011
#define IDC_LIST_STREAM                 1011
#define IDC_LIST_MOTOR                  1011
#define IDC_TREE                        1012
#define IDC_TREEALG                     1012
#define IDC_BTN_FITC                    1012
#define IDC_BTN_RHODAMINE               1013
#define IDC_RADIO_BIT2                  1014
#define IDC_BTN_CY5                     1014
#define IDC_RADIO_BIT4                  1015
#define IDC_BTN_BRIGHTFIELD             1015
#define IDC_RADIO_BIT8                  1016
#define IDC_BTN_DAPI                    1016
#define IDC_BTN_40XOIL                  1016
#define IDC_RADIO_BIT12                 1017
#define IDC_BTN_4X                      1017
#define IDC_EDIT_WIDTH                  1018
#define IDC_BTN_63XOIL                  1018
#define IDC_EDIT_HEIGHT                 1019
#define IDC_BTN_20X                     1019
#define IDC_RADIO_MONOCHROME            1020
#define IDC_BTN_40X                     1020
#define IDC_RADIO_RGB                   1021
#define IDC_RADIO7                      1022
#define IDC_RADIO_CMYK                  1022
#define IDC_BUTTON_PATH                 1023
#define IDC_RADIO_BIN1                  1024
#define IDC_RADIO_BIN2                  1025
#define IDC_RADIO_BIN3                  1026
#define IDC_RADIO_BIN4                  1027
#define IDC_SLIDER_EXPOSURE             1028
#define IDC_BUTTON2                     1029
#define IDC_BUTTON_SNAP                 1029
#define IDC_BTN_COLLAPSE_JOG            1029
#define IDC_BTN_GOTO                    1029
#define IDC_BTN_MEASURE                 1029
#define IDC_BTN_DELETE                  1029
#define IDC_BTN_SNAP                    1029
#define IDC_TAB1                        1030
#define IDC_BUTTON_ZUP                  1031
#define IDC_BUTTON_ZDOWN                1032
#define IDC_BUTTON_INIT                 1033
#define IDC_BTN_EXPAND_STEP             1035
#define IDC_BTN_MOVE                    1035
#define IDC_BTN_COLLAPSE_STEP           1036
#define IDC_BTN_GOHOME                  1037
#define IDC_RADIO_UM                    1038
#define IDC_RADIO_TICKS                 1039
#define IDC_RADIO_STEPS                 1039
#define IDC_RADIO_INCH                  1040
#define IDC_BTN_SETHOME                 1041
#define IDC_BTN_FUNCTION_SINE           1042
#define IDC_EDIT_STEP                   1043
#define IDC_COMBO_PORT                  1044
#define IDC_BTN_CONNECT                 1045
#define IDC_EDIT2                       1046
#define IDC_EDIT_DELAY                  1046
#define IDC_EDIT_COL                    1046
#define IDC_EDIT_STATUS                 1046
#define IDC_EDIT_VOLUME                 1046
#define IDC_EDIT_LOWER                  1046
#define IDC_EDIT_STEPSIZE               1046
#define IDC_EDIT_LOWER2                 1047
#define IDC_EDIT_XGOTO                  1048
#define IDC_BTN_UPDATE                  1049
#define IDC_BTN_GOTOZ                   1050
#define IDC_EDIT_YGOTO                  1051
#define IDC_EDIT_ZGOTO                  1052
#define IDC_EDIT_XPOS                   1054
#define IDC_EDIT_YPOS                   1055
#define IDC_EDIT_ZPOS                   1056
#define IDC_EDIT_ZSTEP                  1057
#define IDC_EDIT_XVEL                   1057
#define IDC_EDIT_FNSTEP                 1058
#define IDC_EDIT_YVEL                   1058
#define IDC_EDIT_FSTEP                  1059
#define IDC_EDIT_ZVEL                   1059
#define IDC_BUTTON3                     1060
#define IDC_BTN_START                   1060
#define IDC_BTN_AUTOEXPOSURE            1060
#define IDC_BTN_LOAD                    1060
#define IDC_BTN_CAPTURE                 1060
#define IDC_EDIT_XVEL_FINE              1060
#define IDC_EDIT_OVERLAP                1061
#define IDC_EDIT_XVEL_COARSE            1061
#define IDC_EDIT_ROW                    1062
#define IDC_EDIT_YVEL_FINE              1062
#define IDC_EDIT_XYVELOCITY             1063
#define IDC_EDIT_ZVEL_FINE              1063
#define IDC_RADIO_RECALL                1064
#define IDC_EDIT_YVEL_COARSE            1064
#define IDC_BUTTON_BROWSE               1065
#define IDC_BTN_BROWSE                  1065
#define IDC_EDIT_ZVEL_COARSE            1065
#define IDC_CHECK1                      1067
#define IDC_CHECK_BRIGHTFIELD           1067
#define IDC_CHECK_VOLUME                1067
#define IDC_CHECK_FRAMERATE             1067
#define IDC_CHECK_XAXIS_STAGE           1067
#define IDC_CHECK_A                     1067
#define IDC_CHECK_RAW                   1067
#define IDC_CHECK_TIMELAPSE             1068
#define IDC_CHECK2                      1068
#define IDC_CHECK_LAPLACIAN             1068
#define IDC_CHECK_CY5                   1068
#define IDC_EDIT_ZVEL_AUTO              1068
#define IDC_CHECK_XAXIS_STICK           1068
#define IDC_CHECK_ENABLE                1069
#define IDC_BTN_OK                      1069
#define IDC_CHECK3                      1069
#define IDC_CHECK_VARIANCE              1069
#define IDC_CHECK_DAPI                  1069
#define IDC_CHECK_ZSTACK                1070
#define IDC_BTN_CANCEL                  1070
#define IDC_CHECK_FITC                  1070
#define IDC_CHECK_AUTOFOCUS             1071
#define IDC_EDIT_TIME                   1071
#define IDC_CHEC_RHODAMINE              1071
#define IDC_CHECK_RHODAMINE             1071
#define IDC_CHECK_MOSAIC                1072
#define IDC_SLIDER_CW                   1072
#define IDC_SLIDER_A                    1072
#define IDC_CHECK_MULTICHANNEL          1073
#define IDC_SLIDER_RB                   1073
#define IDC_SLIDER_B                    1073
#define IDC_SLIDER_MIX                  1074
#define IDC_CHECK_SOBEL                 1074
#define IDC_SLIDER_C                    1074
#define IDC_SLIDER_UV                   1075
#define IDC_SLIDER_D                    1075
#define IDC_EDIT_DISTANCE               1076
#define IDC_EDIT_ROWS                   1077
#define IDC_RADIO_AUTO                  1078
#define IDC_EDIT_NUMSLICE               1079
#define IDC_RADIO_FIXED                 1079
#define IDC_BTN_PREVIEW                 1080
#define IDC_RADIO_MOTORA                1081
#define IDC_RADIO_A                     1081
#define IDC_RADIO_MOTORB                1082
#define IDC_RADIO_B                     1082
#define IDC_RADIO_MOTORC                1083
#define IDC_RADIO_C                     1083
#define IDC_RADIO_MOTORD                1084
#define IDC_RADIO_D                     1084
#define IDC_RADIO2                      1085
#define IDC_RADIO_E                     1085
#define IDC_BTN_DOWNLOAD                1086
#define IDC_BTN_UPLOAD                  1087
#define IDC_RADIO_F                     1087
#define IDC_BTN_10X                     1088
#define IDC_RADIO_D4                    1088
#define IDC_RADIO_FULL                  1088
#define IDC_BTN_EYEPIECE                1089
#define IDC_CHECK_AUTOPHOTOCYCLE        1089
#define IDC_RADIO_HALF                  1089
#define IDC_BTN_10X3                    1090
#define IDC_BTN_CAMERA                  1090
#define IDC_EDIT_RATE                   1090
#define IDC_RADIO_QUARTER               1090
#define IDC_BTN_PATH                    1091
#define IDC_EDIT_INCREASE               1091
#define IDC_RADIO_EIGHTH                1091
#define IDC_EDIT_POSITION               1091
#define IDC_RADIO_STITCHED              1092
#define IDC_RADIO3                      1093
#define IDC_RADIO_UNSTITCHED            1093
#define IDC_RADIO_CW                    1093
#define IDC_RADIO_CW2                   1094
#define IDC_RADIO_CCW                   1094
#define IDC_EDIT_GOTO                   1099
#define IDC_EDIT_UPPER                  1100
#define IDC_EDIT_FRAMERATE              1101
#define IDC_EDIT_UPPER2                 1101
#define IDC_EDIT_SAMEPLERATE            1102
#define IDC_EDIT_SAMPLERATE             1102
#define IDC_EDIT_MAXANGLE               1103
#define IDC_EDIT_MAXDELTA               1104
#define IDC_BUTTON4                     1104
#define IDC_BTN_STOP                    1104
#define IDC_BTN_ZSTACK                  1104
#define IDC_BTN_CLOSE                   1104
#define IDC_EDIT_MAXDISTANCE            1105
#define IDC_EDIT_MAXVELOCITY            1105
#define IDC_CHECK_ZDELAY                1105
#define IDC_BTN_ZSTACK_PREVIEW          1105
#define IDC_EDIT_ROIDIAMETER            1106
#define IDC_EDIT_PIXPERUM               1107
#define IDC_BTN_ZSTACK2                 1108
#define IDC_EDIT_NSLICE                 1109
#define IDC_POLARITY                    1110
#define IDC_CHECK_YAXIS_STAGE           1111
#define IDC_CHECK_ZAXIS_STAGE           1112
#define IDC_POLARITY2                   1113
#define IDC_BTN_ZSTACK_CAPTURE          1113
#define IDC_CHECK_YAXIS_STICK           1114
#define IDC_RADIO_DOWN                  1114
#define IDC_CHECK_ZAXIS_STICK           1115
#define IDC_RADIO_BOTTOM                1115
#define IDC_EDIT_PROFILE                1115
#define IDC_RADIO_MIDPLANE              1116
#define IDC_CHECK_XAXIS                 1116
#define IDC_CHECK_YAXIS                 1117
#define IDC_CHECK_ZAXIS                 1118
#define IDC_CHECK_B                     1119
#define IDC_CHECK_X                     1120
#define IDC_CHECK_Y                     1121
#define IDC_EDIT_Y                      1122
#define IDC_EDIT_UPPER_VEL              1123
#define IDC_EDIT_UPPER_DIM              1124
#define IDC_EDIT_LOWER_DIM              1125
#define IDC_EDIT_LOWER_VEL              1126
#define IDC_EDIT_NUMFRAME               1127
#define IDC_EDIT_NUMREFERENCE           1127
#define IDC_EDIT_SOURCE                 1128
#define IDC_CHECK_RENDERING             1129
#define IDC_BTN_OPEN                    1130
#define ID_WINDOW_CASCADE               32771
#define ID_WINDOW_TILE                  32772
#define ID_FILE_NEW                     32773
#define ID_FILE_OPEN                    32774
#define ID_OPEN_FILE                    32775
#define ID_OPEN_STREAM                  32776
#define ID_FILE_SAVEAS                  32777
#define ID_TOOLS                        32778
#define ID_DEVICES                      32779
#define IDM_FILE_NEW                    32780
#define ID_DEVICES32781                 32781
#define ID_FILE_CLOSE                   32782
#define ID_TOOLS_PARTICLETRACK          32783
#define ID_SETUP_ARCHIVE                32784
#define ID_SAVEAS_                      32785
#define ID_SAVEAS_BMP                   32786
#define ID_VIEW_PROPERTYMANAGER         32787
#define ID_VIEW_COMMANDPROMPT           32788
#define ID_VIEW_MANIFEST                32789
#define ID_VIEW_HISTOGRAMVIEW           32790
#define ID_TOOLS_LOOP                   32791
#define ID_VIEW_DATABAR                 32792
#define ID_VIEW_XBOXLINKER              32793
#define ID_FILE_PATH                    32794
#define ID_PATH_ARCHIVE                 32795
#define ID_FILE_PATHARCHIVE             32796
#define ID_WINDOW_TILEVERTICAL          32797
#define ID_WINDOW_TILE_HORZ             32798
#define ID_WINDOW_TILE_VERT             32799
#define ID_VIEW_ALGORITHMEDITOR         32800
#define ID_DEVICES_CAMERA               32801
#define ID_CAMERA_ZEISS                 32802
#define ID_Menu                         32803
#define ID_CAMERA_WEBCAM                32804
#define ID_DEVICES_FRAMEGRABBER         32805
#define ID_FRAMEGRABBER_BITFLOW         32806
#define ID_DEVICES_CAMERA_ZEISS         32807
#define ID_VIEW_CAMERAPROPERTIES        32808
#define ID_DEVICES_XYZSTAGEPROPERTIES   32809
#define ID_MENU_CAMERAPROPERTIES        32810
#define ID_DEVICES_CAMERAPROPERTIES     32811
#define ID_DEVICES_STAGEPROPERTIES      32812
#define ID_DEVICES_CELLSTRETCHER        32813
#define ID_TOOLS_ZEISSMOSAIC            32814
#define ID_TOOLS_ROIPOLY                32815
#define ID_TOOLS_MOSAIC                 32816
#define ID_TOOLS_ZSTACK                 32817
#define ID_VIEW_MULTI                   32818
#define ID_VIEW_MULTIDIMACQ             32819
#define ID_DEVICES_ZEISSMICROSCOPE      32820
#define ID_DEVICES_REEFWATCHDOG         32821
#define ID_DEVICES_LASERMICROSCOPE      32822
#define ID_Menu32823                    32823
#define ID_ALGORITHM_FLOODFILL          32824
#define ID_ALGORITHM_CHAN               32825
#define ID_TOOLS_ALGORITHM_FLOODFILL    32826
#define ID_TOOLS_TIMELAPSE              32827
#define ID_TOOLS_CROP                   32828
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        190
#define _APS_NEXT_COMMAND_VALUE         32829
#define _APS_NEXT_CONTROL_VALUE         1131
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
